// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Book struct {
	Isbn          string
	CreatedAt     time.Time
	UpdatedAt     time.Time
	Title         string
	Author        string
	CoverImageUrl string
	PublishDate   time.Time
	Pages         int32
	Description   string
}

type User struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Email     string
	Password  string
}
