// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Book struct {
	Isbn          string
	CreatedAt     time.Time
	UpdatedAt     time.Time
	Title         string
	Author        string
	CoverImageUrl string
	PublishDate   sql.NullTime
	Pages         int32
	Description   string
}

type Favourite struct {
	ID        uuid.UUID
	UserID    string
	Isbn      string
	CreatedAt sql.NullTime
}

type Review struct {
	ID          uuid.UUID
	Isbn        string
	UserID      string
	Review      sql.NullString
	Stars       sql.NullFloat64
	Recommended sql.NullBool
	CreatedAt   sql.NullTime
}

type Shelf struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
}

type ShelfBook struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	ShelfID   uuid.UUID
	BookIsbn  string
}

type User struct {
	ID        string
	CreatedAt time.Time
	UpdatedAt time.Time
	Email     string
	Username  string
}

type UserBook struct {
	ID         uuid.UUID
	UserID     string
	Isbn       string
	Status     string
	Progress   int32
	StartedAt  sql.NullTime
	FinishedAt sql.NullTime
	LentTo     sql.NullString
	UpdatedAt  sql.NullTime
}

type UserBookProgress struct {
	ID         uuid.UUID
	UserBookID uuid.UUID
	Progress   int32
	Comment    sql.NullString
	CreatedAt  sql.NullTime
}

type UserShelf struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    string
	ShelfID   uuid.UUID
}
