// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: shelves.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const addBookToShelf = `-- name: AddBookToShelf :one
INSERT INTO shelf_books (id, created_at, updated_at, shelf_id, book_isbn)
VALUES (
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1,
    $2
) RETURNING id, created_at, updated_at, shelf_id, book_isbn
`

type AddBookToShelfParams struct {
	ShelfID  uuid.UUID
	BookIsbn string
}

func (q *Queries) AddBookToShelf(ctx context.Context, arg AddBookToShelfParams) (ShelfBook, error) {
	row := q.db.QueryRowContext(ctx, addBookToShelf, arg.ShelfID, arg.BookIsbn)
	var i ShelfBook
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ShelfID,
		&i.BookIsbn,
	)
	return i, err
}

const createShelf = `-- name: CreateShelf :one
INSERT INTO shelves (id, created_at, updated_at, name) 
VALUES (
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1
) RETURNING id, created_at, updated_at, name
`

func (q *Queries) CreateShelf(ctx context.Context, name string) (Shelf, error) {
	row := q.db.QueryRowContext(ctx, createShelf, name)
	var i Shelf
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
	)
	return i, err
}

const getBookFromShelf = `-- name: GetBookFromShelf :one
SELECT id, created_at, updated_at, shelf_id, book_isbn FROM shelf_books WHERE shelf_id = $1 AND book_isbn = $2
`

type GetBookFromShelfParams struct {
	ShelfID  uuid.UUID
	BookIsbn string
}

func (q *Queries) GetBookFromShelf(ctx context.Context, arg GetBookFromShelfParams) (ShelfBook, error) {
	row := q.db.QueryRowContext(ctx, getBookFromShelf, arg.ShelfID, arg.BookIsbn)
	var i ShelfBook
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ShelfID,
		&i.BookIsbn,
	)
	return i, err
}

const getReadShelf = `-- name: GetReadShelf :one
select shelves.id as shelf_id from user_shelves JOIN users on users.id = user_shelves.user_id JOIN shelves on shelves.id = user_shelves.shelf_id WHERE shelves.name = 'Read' AND users.id = $1
`

func (q *Queries) GetReadShelf(ctx context.Context, id string) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, getReadShelf, id)
	var shelf_id uuid.UUID
	err := row.Scan(&shelf_id)
	return shelf_id, err
}

const getShelf = `-- name: GetShelf :one
SELECT id, created_at, updated_at, name FROM shelves WHERE id = $1
`

func (q *Queries) GetShelf(ctx context.Context, id uuid.UUID) (Shelf, error) {
	row := q.db.QueryRowContext(ctx, getShelf, id)
	var i Shelf
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
	)
	return i, err
}

const getShelvesContainingBook = `-- name: GetShelvesContainingBook :many
SELECT sb.shelf_id
FROM shelf_books sb
INNER JOIN user_shelves us ON sb.shelf_id = us.shelf_id
WHERE sb.book_isbn = $1 AND us.user_id = $2
`

type GetShelvesContainingBookParams struct {
	BookIsbn string
	UserID   string
}

func (q *Queries) GetShelvesContainingBook(ctx context.Context, arg GetShelvesContainingBookParams) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, getShelvesContainingBook, arg.BookIsbn, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var shelf_id uuid.UUID
		if err := rows.Scan(&shelf_id); err != nil {
			return nil, err
		}
		items = append(items, shelf_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsersShelves = `-- name: GetUsersShelves :many
SELECT id, created_at, updated_at, user_id, shelf_id FROM user_shelves WHERE user_id = $1
`

func (q *Queries) GetUsersShelves(ctx context.Context, userID string) ([]UserShelf, error) {
	rows, err := q.db.QueryContext(ctx, getUsersShelves, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserShelf
	for rows.Next() {
		var i UserShelf
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.ShelfID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeBookFromShelf = `-- name: RemoveBookFromShelf :exec
DELETE FROM shelf_books WHERE shelf_id = $1 AND book_isbn = $2
`

type RemoveBookFromShelfParams struct {
	ShelfID  uuid.UUID
	BookIsbn string
}

func (q *Queries) RemoveBookFromShelf(ctx context.Context, arg RemoveBookFromShelfParams) error {
	_, err := q.db.ExecContext(ctx, removeBookFromShelf, arg.ShelfID, arg.BookIsbn)
	return err
}
